Matcap
oppenfuture/three.js pull request #67
Opened 2022-02-10 09:41 UTC by WenjieLiuu

added gltfloader support for matcap material & matcap test

2022-02-10 11:07 UTC, chubei-oppen requested changes
我看不太出来这个模型有没有matcap有啥区别。需要确认一下。

2022-02-10 11:07 UTC, chubei-oppen commented on examples/jsm/loaders/GLTFLoader.js
> +			const kmuExtension = extensions[ EXTENSIONS.OFT_MATERIALS_MATCAP ];
rename kmuExtension to matcapExtension

2022-02-10 11:07 UTC, chubei-oppen commented on examples/jsm/loaders/GLTFLoader.js
> +				material.matcap.flipY = true;
Why?

2022-02-11 02:56 UTC, WenjieLiuu commented
> 我看不太出来这个模型有没有matcap有啥区别。截个对比图看看？
![截屏2022-02-11 上午10 54 29](https://user-images.githubusercontent.com/7301047/153530787-f7cd4feb-0284-4737-8b49-3032ab71a088.png)
这是matcap贴图丢失的效果，类似于meshBasicMaterial

2022-02-11 03:06 UTC, WenjieLiuu commented on examples/jsm/loaders/GLTFLoader.js
> +				material.matcap.flipY = true;
> 

threejs的texture load的时候filpY默认是true，应该是对应webgl的uv空间。但是gltfloader里面把所有texture的flipY改成了false，我猜可能是gltf-blender-io导出的时候把uv.v flip了？这个不太确定。所以这里需要把matcap的flipY再设置回true才能保证效果跟threejs editor里的一致

2022-02-11 03:38 UTC, chubei-oppen commented on examples/jsm/loaders/GLTFLoader.js
> +				material.matcap.flipY = true;
把这些加到comment里吧

2022-02-11 07:45 UTC, chubei-oppen approved these changes

2022-02-11 07:46 UTC, merged